In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [2]:
df = pd.read_csv('hiring.csv')

In [3]:
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [4]:
df['experience'].fillna('zero', inplace=True)
df

C:\Users\vaibh\AppData\Local\Temp\ipykernel_4216\1763933233.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['experience'].fillna('zero', inplace=True)

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   experience                  8 non-null      object
 1   test_score(out of 10)       7 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64
 3   salary($)                   8 non-null      int64
dtypes: float64(1), int64(2), object(1)
memory usage: 388.0+ bytes

In [6]:
df['test_score(out of 10)'].fillna(df['test_score(out of 10)'].mean(), inplace = True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   experience                  8 non-null      object
 1   test_score(out of 10)       8 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64
 3   salary($)                   8 non-null      int64
dtypes: float64(1), int64(2), object(1)
memory usage: 388.0+ bytes

C:\Users\vaibh\AppData\Local\Temp\ipykernel_4216\2299295613.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['test_score(out of 10)'].fillna(df['test_score(out of 10)'].mean(), inplace = True)

In [7]:
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero               8.000000                           9      50000
1       zero               8.000000                           6      45000
2       five               6.000000                           7      60000
3        two              10.000000                          10      65000
4      seven               9.000000                           6      70000
5      three               7.000000                          10      62000
6        ten               7.857143                           7      72000
7     eleven               7.000000                           8      80000

In [8]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].round(0).astype('int')

In [9]:
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                      8                           9      50000
1       zero                      8                           6      45000
2       five                      6                           7      60000
3        two                     10                          10      65000
4      seven                      9                           6      70000
5      three                      7                          10      62000
6        ten                      8                           7      72000
7     eleven                      7                           8      80000

In [10]:
from word2number import w2n
df.experience = df.experience.apply(w2n.word_to_num)
df.head()

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                      8                           9      50000
1           0                      8                           6      45000
2           5                      6                           7      60000
3           2                     10                          10      65000
4           7                      9                           6      70000

In [11]:
lr = linear_model.LinearRegression()

In [12]:
lr.fit(df.drop('salary($)', axis='columns'), df[['salary($)']])

LinearRegression()

In [13]:
lr.coef_

array([[2812.95487627, 1845.70596798, 2205.24017467]])

In [14]:
lr.intercept_

array([17737.26346434])

In [16]:
lr.predict([[2,9,6]])

C:\Users\vaibh\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[53205.96797671]])

In [18]:
lr.predict([[12,10,10]])

C:\Users\vaibh\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[92002.18340611]])